type Author {
  idA: ID
  name: String
  age: Int
  nationality: String
  books: [Book]
}

type Book {
  idBook: ID
  title: String
  publicationYear: Int
  language: String
  nbPages: Int
  author: Author
  category: Category
}

type Category {
  idC: ID
  categoryName: String
  parentCategory: Category
  subCategories: [Category]
}

type PageInfo {
  totalPages: Int
  totalElements: Int
}

type BookPage {
  content: [Book]
  pageInfo: PageInfo
}
union SearchResult = Book | Author | Category
type SearchPage {
  content: [SearchResult]
  pageInfo: PageInfo
}
type Query{
  listBooks(
    page: Int
    size: Int
    year: Int
    language: String
    categoryId: ID): BookPage
  booksByAuthor(authorId: ID!): [Book]
  search(keyword: String!, type: String, page: Int, size: Int): SearchPage
}

type Mutation {
  addBook(
    title: String!,
    publicationYear: Int!,
    language: String!,
    nbPages: Int!,
    authorId: ID!,
    categoryId: ID!
  ): Book

  deleteAuthor(authorId: ID!): Boolean
}
