-- Sample Categories (20 total)
INSERT INTO category (idc, category_name, parent_category_idc) VALUES (1, 'Fiction', NULL);
INSERT INTO category (idc, category_name, parent_category_idc) VALUES (2, 'Science Fiction', 1);
INSERT INTO category (idc, category_name, parent_category_idc) VALUES (3, 'Fantasy', 1);
INSERT INTO category (idc, category_name, parent_category_idc) VALUES (4, 'Mystery', 1);
INSERT INTO category (idc, category_name, parent_category_idc) VALUES (5, 'Thriller', 1);
INSERT INTO category (idc, category_name, parent_category_idc) VALUES (6, 'Romance', 1);
INSERT INTO category (idc, category_name, parent_category_idc) VALUES (7, 'Non-Fiction', NULL);
INSERT INTO category (idc, category_name, parent_category_idc) VALUES (8, 'Technology', 7);
INSERT INTO category (idc, category_name, parent_category_idc) VALUES (9, 'History', 7);
INSERT INTO category (idc, category_name, parent_category_idc) VALUES (10, 'Biography', 7);
INSERT INTO category (idc, category_name, parent_category_idc) VALUES (11, 'Science', 7);
INSERT INTO category (idc, category_name, parent_category_idc) VALUES (12, 'Philosophy', 7);
INSERT INTO category (idc, category_name, parent_category_idc) VALUES (13, 'Psychology', 7);
INSERT INTO category (idc, category_name, parent_category_idc) VALUES (14, 'Business', 7);
INSERT INTO category (idc, category_name, parent_category_idc) VALUES (15, 'Self-Help', 7);
INSERT INTO category (idc, category_name, parent_category_idc) VALUES (16, 'Young Adult', NULL);
INSERT INTO category (idc, category_name, parent_category_idc) VALUES (17, 'Children', NULL);
INSERT INTO category (idc, category_name, parent_category_idc) VALUES (18, 'Poetry', NULL);
INSERT INTO category (idc, category_name, parent_category_idc) VALUES (19, 'Drama', NULL);
INSERT INTO category (idc, category_name, parent_category_idc) VALUES (20, 'Comics', NULL);

-- Sample Authors (70 total)
INSERT INTO author (ida, name, age, nationality) VALUES (1, 'Isaac Asimov', 72, 'American');
INSERT INTO author (ida, name, age, nationality) VALUES (2, 'Arthur C. Clarke', 90, 'British');
INSERT INTO author (ida, name, age, nationality) VALUES (3, 'Philip K. Dick', 53, 'American');
INSERT INTO author (ida, name, age, nationality) VALUES (4, 'Yuval Noah Harari', 48, 'Israeli');
INSERT INTO author (ida, name, age, nationality) VALUES (5, 'Walter Isaacson', 71, 'American');
INSERT INTO author (ida, name, age, nationality) VALUES (6, 'J.K. Rowling', 59, 'British');
INSERT INTO author (ida, name, age, nationality) VALUES (7, 'George R.R. Martin', 76, 'American');
INSERT INTO author (ida, name, age, nationality) VALUES (8, 'Stephen King', 77, 'American');
INSERT INTO author (ida, name, age, nationality) VALUES (9, 'Agatha Christie', 85, 'British');
INSERT INTO author (ida, name, age, nationality) VALUES (10, 'Dan Brown', 60, 'American');
INSERT INTO author (ida, name, age, nationality) VALUES (11, 'J.R.R. Tolkien', 81, 'British');
INSERT INTO author (ida, name, age, nationality) VALUES (12, 'Ernest Hemingway', 61, 'American');
INSERT INTO author (ida, name, age, nationality) VALUES (13, 'F. Scott Fitzgerald', 44, 'American');
INSERT INTO author (ida, name, age, nationality) VALUES (14, 'Jane Austen', 41, 'British');
INSERT INTO author (ida, name, age, nationality) VALUES (15, 'Charles Dickens', 58, 'British');
INSERT INTO author (ida, name, age, nationality) VALUES (16, 'Mark Twain', 74, 'American');
INSERT INTO author (ida, name, age, nationality) VALUES (17, 'Leo Tolstoy', 82, 'Russian');
INSERT INTO author (ida, name, age, nationality) VALUES (18, 'Fyodor Dostoevsky', 59, 'Russian');
INSERT INTO author (ida, name, age, nationality) VALUES (19, 'Gabriel García Márquez', 87, 'Colombian');
INSERT INTO author (ida, name, age, nationality) VALUES (20, 'Haruki Murakami', 75, 'Japanese');
INSERT INTO author (ida, name, age, nationality) VALUES (21, 'Margaret Atwood', 85, 'Canadian');
INSERT INTO author (ida, name, age, nationality) VALUES (22, 'Neil Gaiman', 64, 'British');
INSERT INTO author (ida, name, age, nationality) VALUES (23, 'Terry Pratchett', 66, 'British');
INSERT INTO author (ida, name, age, nationality) VALUES (24, 'Ursula K. Le Guin', 88, 'American');
INSERT INTO author (ida, name, age, nationality) VALUES (25, 'Ray Bradbury', 91, 'American');
INSERT INTO author (ida, name, age, nationality) VALUES (26, 'Kurt Vonnegut', 84, 'American');
INSERT INTO author (ida, name, age, nationality) VALUES (27, 'Douglas Adams', 49, 'British');
INSERT INTO author (ida, name, age, nationality) VALUES (28, 'Orson Scott Card', 73, 'American');
INSERT INTO author (ida, name, age, nationality) VALUES (29, 'Frank Herbert', 65, 'American');
INSERT INTO author (ida, name, age, nationality) VALUES (30, 'Robert A. Heinlein', 80, 'American');
INSERT INTO author (ida, name, age, nationality) VALUES (31, 'Carl Sagan', 62, 'American');
INSERT INTO author (ida, name, age, nationality) VALUES (32, 'Richard Dawkins', 83, 'British');
INSERT INTO author (ida, name, age, nationality) VALUES (33, 'Stephen Hawking', 76, 'British');
INSERT INTO author (ida, name, age, nationality) VALUES (34, 'Malcolm Gladwell', 61, 'Canadian');
INSERT INTO author (ida, name, age, nationality) VALUES (35, 'Daniel Kahneman', 90, 'Israeli');
INSERT INTO author (ida, name, age, nationality) VALUES (36, 'Nassim Nicholas Taleb', 64, 'Lebanese');
INSERT INTO author (ida, name, age, nationality) VALUES (37, 'Viktor Frankl', 92, 'Austrian');
INSERT INTO author (ida, name, age, nationality) VALUES (38, 'Dale Carnegie', 66, 'American');
INSERT INTO author (ida, name, age, nationality) VALUES (39, 'Napoleon Hill', 87, 'American');
INSERT INTO author (ida, name, age, nationality) VALUES (40, 'Robert Kiyosaki', 77, 'American');
INSERT INTO author (ida, name, age, nationality) VALUES (41, 'Simon Sinek', 51, 'British');
INSERT INTO author (ida, name, age, nationality) VALUES (42, 'Brené Brown', 59, 'American');
INSERT INTO author (ida, name, age, nationality) VALUES (43, 'Michelle Obama', 60, 'American');
INSERT INTO author (ida, name, age, nationality) VALUES (44, 'Barack Obama', 63, 'American');
INSERT INTO author (ida, name, age, nationality) VALUES (45, 'Tara Westover', 38, 'American');
INSERT INTO author (ida, name, age, nationality) VALUES (46, 'Suzanne Collins', 62, 'American');
INSERT INTO author (ida, name, age, nationality) VALUES (47, 'Veronica Roth', 36, 'American');
INSERT INTO author (ida, name, age, nationality) VALUES (48, 'Cassandra Clare', 51, 'American');
INSERT INTO author (ida, name, age, nationality) VALUES (49, 'Rick Riordan', 60, 'American');
INSERT INTO author (ida, name, age, nationality) VALUES (50, 'John Green', 47, 'American');
INSERT INTO author (ida, name, age, nationality) VALUES (51, 'Rainbow Rowell', 50, 'American');
INSERT INTO author (ida, name, age, nationality) VALUES (52, 'Colleen Hoover', 45, 'American');
INSERT INTO author (ida, name, age, nationality) VALUES (53, 'Nicholas Sparks', 59, 'American');
INSERT INTO author (ida, name, age, nationality) VALUES (54, 'Nora Roberts', 74, 'American');
INSERT INTO author (ida, name, age, nationality) VALUES (55, 'James Patterson', 77, 'American');
INSERT INTO author (ida, name, age, nationality) VALUES (56, 'Lee Child', 69, 'British');
INSERT INTO author (ida, name, age, nationality) VALUES (57, 'John Grisham', 69, 'American');
INSERT INTO author (ida, name, age, nationality) VALUES (58, 'Michael Connelly', 68, 'American');
INSERT INTO author (ida, name, age, nationality) VALUES (59, 'Gillian Flynn', 53, 'American');
INSERT INTO author (ida, name, age, nationality) VALUES (60, 'Paula Hawkins', 52, 'British');
INSERT INTO author (ida, name, age, nationality) VALUES (61, 'Stieg Larsson', 50, 'Swedish');
INSERT INTO author (ida, name, age, nationality) VALUES (62, 'Jo Nesbø', 64, 'Norwegian');
INSERT INTO author (ida, name, age, nationality) VALUES (63, 'Henning Mankell', 67, 'Swedish');
INSERT INTO author (ida, name, age, nationality) VALUES (64, 'Chimamanda Ngozi Adichie', 47, 'Nigerian');
INSERT INTO author (ida, name, age, nationality) VALUES (65, 'Chinua Achebe', 82, 'Nigerian');
INSERT INTO author (ida, name, age, nationality) VALUES (66, 'Salman Rushdie', 77, 'British');
INSERT INTO author (ida, name, age, nationality) VALUES (67, 'Kazuo Ishiguro', 70, 'British');
INSERT INTO author (ida, name, age, nationality) VALUES (68, 'Toni Morrison', 88, 'American');
INSERT INTO author (ida, name, age, nationality) VALUES (69, 'Maya Angelou', 86, 'American');
INSERT INTO author (ida, name, age, nationality) VALUES (70, 'Alice Walker', 80, 'American');

-- Sample Books (170 total)
INSERT INTO book (id_book, title, publication_year, language, nb_pages, author_ida, category_idc) VALUES (1, 'Foundation', 1951, 'English', 255, 1, 2);
INSERT INTO book (id_book, title, publication_year, language, nb_pages, author_ida, category_idc) VALUES (2, 'I, Robot', 1950, 'English', 224, 1, 2);
INSERT INTO book (id_book, title, publication_year, language, nb_pages, author_ida, category_idc) VALUES (3, 'The End of Eternity', 1955, 'English', 191, 1, 2);
INSERT INTO book (id_book, title, publication_year, language, nb_pages, author_ida, category_idc) VALUES (4, '2001: A Space Odyssey', 1968, 'English', 297, 2, 2);
INSERT INTO book (id_book, title, publication_year, language, nb_pages, author_ida, category_idc) VALUES (5, 'Rendezvous with Rama', 1973, 'English', 243, 2, 2);
INSERT INTO book (id_book, title, publication_year, language, nb_pages, author_ida, category_idc) VALUES (6, 'Childhood''s End', 1953, 'English', 214, 2, 2);
INSERT INTO book (id_book, title, publication_year, language, nb_pages, author_ida, category_idc) VALUES (7, 'Do Androids Dream of Electric Sheep?', 1968, 'English', 210, 3, 2);
INSERT INTO book (id_book, title, publication_year, language, nb_pages, author_ida, category_idc) VALUES (8, 'The Man in the High Castle', 1962, 'English', 259, 3, 2);
INSERT INTO book (id_book, title, publication_year, language, nb_pages, author_ida, category_idc) VALUES (9, 'Ubik', 1969, 'English', 202, 3, 2);
INSERT INTO book (id_book, title, publication_year, language, nb_pages, author_ida, category_idc) VALUES (10, 'Sapiens', 2011, 'English', 443, 4, 9);
INSERT INTO book (id_book, title, publication_year, language, nb_pages, author_ida, category_idc) VALUES (11, 'Homo Deus', 2015, 'English', 440, 4, 9);
INSERT INTO book (id_book, title, publication_year, language, nb_pages, author_ida, category_idc) VALUES (12, '21 Lessons for the 21st Century', 2018, 'English', 372, 4, 12);
INSERT INTO book (id_book, title, publication_year, language, nb_pages, author_ida, category_idc) VALUES (13, 'Steve Jobs', 2011, 'English', 656, 5, 10);
INSERT INTO book (id_book, title, publication_year, language, nb_pages, author_ida, category_idc) VALUES (14, 'Einstein: His Life and Universe', 2007, 'English', 675, 5, 10);
INSERT INTO book (id_book, title, publication_year, language, nb_pages, author_ida, category_idc) VALUES (15, 'Leonardo da Vinci', 2017, 'English', 624, 5, 10);
INSERT INTO book (id_book, title, publication_year, language, nb_pages, author_ida, category_idc) VALUES (16, 'Harry Potter and the Philosopher''s Stone', 1997, 'English', 223, 6, 3);
INSERT INTO book (id_book, title, publication_year, language, nb_pages, author_ida, category_idc) VALUES (17, 'Harry Potter and the Chamber of Secrets', 1998, 'English', 251, 6, 3);
INSERT INTO book (id_book, title, publication_year, language, nb_pages, author_ida, category_idc) VALUES (18, 'Harry Potter and the Prisoner of Azkaban', 1999, 'English', 317, 6, 3);
INSERT INTO book (id_book, title, publication_year, language, nb_pages, author_ida, category_idc) VALUES (19, 'A Game of Thrones', 1996, 'English', 694, 7, 3);
INSERT INTO book (id_book, title, publication_year, language, nb_pages, author_ida, category_idc) VALUES (20, 'A Clash of Kings', 1998, 'English', 761, 7, 3);
INSERT INTO book (id_book, title, publication_year, language, nb_pages, author_ida, category_idc) VALUES (21, 'A Storm of Swords', 2000, 'English', 973, 7, 3);
INSERT INTO book (id_book, title, publication_year, language, nb_pages, author_ida, category_idc) VALUES (22, 'The Shining', 1977, 'English', 447, 8, 5);
INSERT INTO book (id_book, title, publication_year, language, nb_pages, author_ida, category_idc) VALUES (23, 'It', 1986, 'English', 1138, 8, 5);
INSERT INTO book (id_book, title, publication_year, language, nb_pages, author_ida, category_idc) VALUES (24, 'The Stand', 1978, 'English', 823, 8, 5);
INSERT INTO book (id_book, title, publication_year, language, nb_pages, author_ida, category_idc) VALUES (25, 'Murder on the Orient Express', 1934, 'English', 256, 9, 4);
INSERT INTO book (id_book, title, publication_year, language, nb_pages, author_ida, category_idc) VALUES (26, 'And Then There Were None', 1939, 'English', 272, 9, 4);
INSERT INTO book (id_book, title, publication_year, language, nb_pages, author_ida, category_idc) VALUES (27, 'Death on the Nile', 1937, 'English', 288, 9, 4);
INSERT INTO book (id_book, title, publication_year, language, nb_pages, author_ida, category_idc) VALUES (28, 'The Da Vinci Code', 2003, 'English', 489, 10, 5);
INSERT INTO book (id_book, title, publication_year, language, nb_pages, author_ida, category_idc) VALUES (29, 'Angels & Demons', 2000, 'English', 616, 10, 5);
INSERT INTO book (id_book, title, publication_year, language, nb_pages, author_ida, category_idc) VALUES (30, 'The Lost Symbol', 2009, 'English', 528, 10, 5);
INSERT INTO book (id_book, title, publication_year, language, nb_pages, author_ida, category_idc) VALUES (31, 'The Lord of the Rings', 1954, 'English', 1178, 11, 3);
INSERT INTO book (id_book, title, publication_year, language, nb_pages, author_ida, category_idc) VALUES (32, 'The Hobbit', 1937, 'English', 310, 11, 3);
INSERT INTO book (id_book, title, publication_year, language, nb_pages, author_ida, category_idc) VALUES (33, 'The Silmarillion', 1977, 'English', 365, 11, 3);
INSERT INTO book (id_book, title, publication_year, language, nb_pages, author_ida, category_idc) VALUES (34, 'The Old Man and the Sea', 1952, 'English', 127, 12, 1);
INSERT INTO book (id_book, title, publication_year, language, nb_pages, author_ida, category_idc) VALUES (35, 'A Farewell to Arms', 1929, 'English', 332, 12, 1);
INSERT INTO book (id_book, title, publication_year, language, nb_pages, author_ida, category_idc) VALUES (36, 'For Whom the Bell Tolls', 1940, 'English', 471, 12, 1);
INSERT INTO book (id_book, title, publication_year, language, nb_pages, author_ida, category_idc) VALUES (37, 'The Great Gatsby', 1925, 'English', 180, 13, 1);
INSERT INTO book (id_book, title, publication_year, language, nb_pages, author_ida, category_idc) VALUES (38, 'Tender Is the Night', 1934, 'English', 317, 13, 1);
INSERT INTO book (id_book, title, publication_year, language, nb_pages, author_ida, category_idc) VALUES (39, 'Pride and Prejudice', 1813, 'English', 279, 14, 6);
INSERT INTO book (id_book, title, publication_year, language, nb_pages, author_ida, category_idc) VALUES (40, 'Sense and Sensibility', 1811, 'English', 409, 14, 6);
INSERT INTO book (id_book, title, publication_year, language, nb_pages, author_ida, category_idc) VALUES (41, 'Emma', 1815, 'English', 474, 14, 6);
INSERT INTO book (id_book, title, publication_year, language, nb_pages, author_ida, category_idc) VALUES (42, 'Great Expectations', 1861, 'English', 505, 15, 1);
INSERT INTO book (id_book, title, publication_year, language, nb_pages, author_ida, category_idc) VALUES (43, 'A Tale of Two Cities', 1859, 'English', 448, 15, 1);
INSERT INTO book (id_book, title, publication_year, language, nb_pages, author_ida, category_idc) VALUES (44, 'Oliver Twist', 1838, 'English', 608, 15, 1);
INSERT INTO book (id_book, title, publication_year, language, nb_pages, author_ida, category_idc) VALUES (45, 'The Adventures of Tom Sawyer', 1876, 'English', 274, 16, 17);
INSERT INTO book (id_book, title, publication_year, language, nb_pages, author_ida, category_idc) VALUES (46, 'Adventures of Huckleberry Finn', 1884, 'English', 366, 16, 17);
INSERT INTO book (id_book, title, publication_year, language, nb_pages, author_ida, category_idc) VALUES (47, 'War and Peace', 1869, 'English', 1225, 17, 1);
INSERT INTO book (id_book, title, publication_year, language, nb_pages, author_ida, category_idc) VALUES (48, 'Anna Karenina', 1877, 'English', 864, 17, 1);
INSERT INTO book (id_book, title, publication_year, language, nb_pages, author_ida, category_idc) VALUES (49, 'Crime and Punishment', 1866, 'English', 671, 18, 1);
INSERT INTO book (id_book, title, publication_year, language, nb_pages, author_ida, category_idc) VALUES (50, 'The Brothers Karamazov', 1880, 'English', 796, 18, 1);
INSERT INTO book (id_book, title, publication_year, language, nb_pages, author_ida, category_idc) VALUES (51, 'One Hundred Years of Solitude', 1967, 'English', 417, 19, 1);
INSERT INTO book (id_book, title, publication_year, language, nb_pages, author_ida, category_idc) VALUES (52, 'Love in the Time of Cholera', 1985, 'English', 348, 19, 6);
INSERT INTO book (id_book, title, publication_year, language, nb_pages, author_ida, category_idc) VALUES (53, 'Norwegian Wood', 1987, 'English', 296, 20, 6);
INSERT INTO book (id_book, title, publication_year, language, nb_pages, author_ida, category_idc) VALUES (54, 'Kafka on the Shore', 2002, 'English', 505, 20, 1);
INSERT INTO book (id_book, title, publication_year, language, nb_pages, author_ida, category_idc) VALUES (55, '1Q84', 2009, 'English', 925, 20, 1);
INSERT INTO book (id_book, title, publication_year, language, nb_pages, author_ida, category_idc) VALUES (56, 'The Handmaid''s Tale', 1985, 'English', 311, 21, 2);
INSERT INTO book (id_book, title, publication_year, language, nb_pages, author_ida, category_idc) VALUES (57, 'Oryx and Crake', 2003, 'English', 376, 21, 2);
INSERT INTO book (id_book, title, publication_year, language, nb_pages, author_ida, category_idc) VALUES (58, 'American Gods', 2001, 'English', 635, 22, 3);
INSERT INTO book (id_book, title, publication_year, language, nb_pages, author_ida, category_idc) VALUES (59, 'Good Omens', 1990, 'English', 383, 22, 3);
INSERT INTO book (id_book, title, publication_year, language, nb_pages, author_ida, category_idc) VALUES (60, 'The Graveyard Book', 2008, 'English', 312, 22, 3);
INSERT INTO book (id_book, title, publication_year, language, nb_pages, author_ida, category_idc) VALUES (61, 'The Color of Magic', 1983, 'English', 206, 23, 3);
INSERT INTO book (id_book, title, publication_year, language, nb_pages, author_ida, category_idc) VALUES (62, 'Guards! Guards!', 1989, 'English', 376, 23, 3);
INSERT INTO book (id_book, title, publication_year, language, nb_pages, author_ida, category_idc) VALUES (63, 'The Left Hand of Darkness', 1969, 'English', 304, 24, 2);
INSERT INTO book (id_book, title, publication_year, language, nb_pages, author_ida, category_idc) VALUES (64, 'The Dispossessed', 1974, 'English', 387, 24, 2);
INSERT INTO book (id_book, title, publication_year, language, nb_pages, author_ida, category_idc) VALUES (65, 'Fahrenheit 451', 1953, 'English', 249, 25, 2);
INSERT INTO book (id_book, title, publication_year, language, nb_pages, author_ida, category_idc) VALUES (66, 'The Martian Chronicles', 1950, 'English', 222, 25, 2);
INSERT INTO book (id_book, title, publication_year, language, nb_pages, author_ida, category_idc) VALUES (67, 'Slaughterhouse-Five', 1969, 'English', 275, 26, 2);
INSERT INTO book (id_book, title, publication_year, language, nb_pages, author_ida, category_idc) VALUES (68, 'Cat''s Cradle', 1963, 'English', 304, 26, 2);
INSERT INTO book (id_book, title, publication_year, language, nb_pages, author_ida, category_idc) VALUES (69, 'The Hitchhiker''s Guide to the Galaxy', 1979, 'English', 224, 27, 2);
INSERT INTO book (id_book, title, publication_year, language, nb_pages, author_ida, category_idc) VALUES (70, 'The Restaurant at the End of the Universe', 1980, 'English', 250, 27, 2);
INSERT INTO book (id_book, title, publication_year, language, nb_pages, author_ida, category_idc) VALUES (71, 'Ender''s Game', 1985, 'English', 324, 28, 2);
INSERT INTO book (id_book, title, publication_year, language, nb_pages, author_ida, category_idc) VALUES (72, 'Speaker for the Dead', 1986, 'English', 415, 28, 2);
INSERT INTO book (id_book, title, publication_year, language, nb_pages, author_ida, category_idc) VALUES (73, 'Dune', 1965, 'English', 688, 29, 2);
INSERT INTO book (id_book, title, publication_year, language, nb_pages, author_ida, category_idc) VALUES (74, 'Dune Messiah', 1969, 'English', 331, 29, 2);
INSERT INTO book (id_book, title, publication_year, language, nb_pages, author_ida, category_idc) VALUES (75, 'Starship Troopers', 1959, 'English', 263, 30, 2);
INSERT INTO book (id_book, title, publication_year, language, nb_pages, author_ida, category_idc) VALUES (76, 'Stranger in a Strange Land', 1961, 'English', 525, 30, 2);
INSERT INTO book (id_book, title, publication_year, language, nb_pages, author_ida, category_idc) VALUES (77, 'Cosmos', 1980, 'English', 365, 31, 11);
INSERT INTO book (id_book, title, publication_year, language, nb_pages, author_ida, category_idc) VALUES (78, 'Contact', 1985, 'English', 434, 31, 2);
INSERT INTO book (id_book, title, publication_year, language, nb_pages, author_ida, category_idc) VALUES (79, 'The Selfish Gene', 1976, 'English', 360, 32, 11);
INSERT INTO book (id_book, title, publication_year, language, nb_pages, author_ida, category_idc) VALUES (80, 'The God Delusion', 2006, 'English', 374, 32, 12);
INSERT INTO book (id_book, title, publication_year, language, nb_pages, author_ida, category_idc) VALUES (81, 'A Brief History of Time', 1988, 'English', 256, 33, 11);
INSERT INTO book (id_book, title, publication_year, language, nb_pages, author_ida, category_idc) VALUES (82, 'The Universe in a Nutshell', 2001, 'English', 216, 33, 11);
INSERT INTO book (id_book, title, publication_year, language, nb_pages, author_ida, category_idc) VALUES (83, 'Outliers', 2008, 'English', 309, 34, 13);
INSERT INTO book (id_book, title, publication_year, language, nb_pages, author_ida, category_idc) VALUES (84, 'The Tipping Point', 2000, 'English', 301, 34, 13);
INSERT INTO book (id_book, title, publication_year, language, nb_pages, author_ida, category_idc) VALUES (85, 'Blink', 2005, 'English', 296, 34, 13);
INSERT INTO book (id_book, title, publication_year, language, nb_pages, author_ida, category_idc) VALUES (86, 'Thinking, Fast and Slow', 2011, 'English', 499, 35, 13);
INSERT INTO book (id_book, title, publication_year, language, nb_pages, author_ida, category_idc) VALUES (87, 'The Black Swan', 2007, 'English', 444, 36, 14);
INSERT INTO book (id_book, title, publication_year, language, nb_pages, author_ida, category_idc) VALUES (88, 'Antifragile', 2012, 'English', 519, 36, 14);
INSERT INTO book (id_book, title, publication_year, language, nb_pages, author_ida, category_idc) VALUES (89, 'Man''s Search for Meaning', 1946, 'English', 165, 37, 13);
INSERT INTO book (id_book, title, publication_year, language, nb_pages, author_ida, category_idc) VALUES (90, 'How to Win Friends and Influence People', 1936, 'English', 288, 38, 15);
INSERT INTO book (id_book, title, publication_year, language, nb_pages, author_ida, category_idc) VALUES (91, 'Think and Grow Rich', 1937, 'English', 238, 39, 15);
INSERT INTO book (id_book, title, publication_year, language, nb_pages, author_ida, category_idc) VALUES (92, 'Rich Dad Poor Dad', 1997, 'English', 336, 40, 14);
INSERT INTO book (id_book, title, publication_year, language, nb_pages, author_ida, category_idc) VALUES (93, 'Start with Why', 2009, 'English', 256, 41, 14);
INSERT INTO book (id_book, title, publication_year, language, nb_pages, author_ida, category_idc) VALUES (94, 'Leaders Eat Last', 2014, 'English', 368, 41, 14);
INSERT INTO book (id_book, title, publication_year, language, nb_pages, author_ida, category_idc) VALUES (95, 'Daring Greatly', 2012, 'English', 320, 42, 15);
INSERT INTO book (id_book, title, publication_year, language, nb_pages, author_ida, category_idc) VALUES (96, 'The Gifts of Imperfection', 2010, 'English', 137, 42, 15);
INSERT INTO book (id_book, title, publication_year, language, nb_pages, author_ida, category_idc) VALUES (97, 'Becoming', 2018, 'English', 448, 43, 10);
INSERT INTO book (id_book, title, publication_year, language, nb_pages, author_ida, category_idc) VALUES (98, 'A Promised Land', 2020, 'English', 768, 44, 10);
INSERT INTO book (id_book, title, publication_year, language, nb_pages, author_ida, category_idc) VALUES (99, 'Educated', 2018, 'English', 334, 45, 10);
INSERT INTO book (id_book, title, publication_year, language, nb_pages, author_ida, category_idc) VALUES (100, 'The Hunger Games', 2008, 'English', 374, 46, 16);
INSERT INTO book (id_book, title, publication_year, language, nb_pages, author_ida, category_idc) VALUES (101, 'Catching Fire', 2009, 'English', 391, 46, 16);
INSERT INTO book (id_book, title, publication_year, language, nb_pages, author_ida, category_idc) VALUES (102, 'Mockingjay', 2010, 'English', 390, 46, 16);
INSERT INTO book (id_book, title, publication_year, language, nb_pages, author_ida, category_idc) VALUES (103, 'Divergent', 2011, 'English', 487, 47, 16);
INSERT INTO book (id_book, title, publication_year, language, nb_pages, author_ida, category_idc) VALUES (104, 'Insurgent', 2012, 'English', 525, 47, 16);
INSERT INTO book (id_book, title, publication_year, language, nb_pages, author_ida, category_idc) VALUES (105, 'Allegiant', 2013, 'English', 526, 47, 16);
INSERT INTO book (id_book, title, publication_year, language, nb_pages, author_ida, category_idc) VALUES (106, 'City of Bones', 2007, 'English', 485, 48, 16);
INSERT INTO book (id_book, title, publication_year, language, nb_pages, author_ida, category_idc) VALUES (107, 'City of Ashes', 2008, 'English', 453, 48, 16);
INSERT INTO book (id_book, title, publication_year, language, nb_pages, author_ida, category_idc) VALUES (108, 'The Lightning Thief', 2005, 'English', 377, 49, 16);
INSERT INTO book (id_book, title, publication_year, language, nb_pages, author_ida, category_idc) VALUES (109, 'The Sea of Monsters', 2006, 'English', 279, 49, 16);
INSERT INTO book (id_book, title, publication_year, language, nb_pages, author_ida, category_idc) VALUES (110, 'The Fault in Our Stars', 2012, 'English', 313, 50, 16);
INSERT INTO book (id_book, title, publication_year, language, nb_pages, author_ida, category_idc) VALUES (111, 'Looking for Alaska', 2005, 'English', 221, 50, 16);
INSERT INTO book (id_book, title, publication_year, language, nb_pages, author_ida, category_idc) VALUES (112, 'Eleanor & Park', 2013, 'English', 328, 51, 16);
INSERT INTO book (id_book, title, publication_year, language, nb_pages, author_ida, category_idc) VALUES (113, 'Fangirl', 2013, 'English', 433, 51, 16);
INSERT INTO book (id_book, title, publication_year, language, nb_pages, author_ida, category_idc) VALUES (114, 'It Ends with Us', 2016, 'English', 384, 52, 6);
INSERT INTO book (id_book, title, publication_year, language, nb_pages, author_ida, category_idc) VALUES (115, 'Verity', 2018, 'English', 336, 52, 5);
INSERT INTO book (id_book, title, publication_year, language, nb_pages, author_ida, category_idc) VALUES (116, 'The Notebook', 1996, 'English', 214, 53, 6);
INSERT INTO book (id_book, title, publication_year, language, nb_pages, author_ida, category_idc) VALUES (117, 'A Walk to Remember', 1999, 'English', 240, 53, 6);
INSERT INTO book (id_book, title, publication_year, language, nb_pages, author_ida, category_idc) VALUES (118, 'The Last Song', 2009, 'English', 416, 53, 6);
INSERT INTO book (id_book, title, publication_year, language, nb_pages, author_ida, category_idc) VALUES (119, 'Vision in White', 2009, 'English', 357, 54, 6);
INSERT INTO book (id_book, title, publication_year, language, nb_pages, author_ida, category_idc) VALUES (120, 'Blue Dahlia', 2004, 'English', 368, 54, 6);
INSERT INTO book (id_book, title, publication_year, language, nb_pages, author_ida, category_idc) VALUES (121, 'Along Came a Spider', 1993, 'English', 435, 55, 5);
INSERT INTO book (id_book, title, publication_year, language, nb_pages, author_ida, category_idc) VALUES (122, 'Kiss the Girls', 1995, 'English', 451, 55, 5);
INSERT INTO book (id_book, title, publication_year, language, nb_pages, author_ida, category_idc) VALUES (123, 'Killing Floor', 1997, 'English', 541, 56, 5);
INSERT INTO book (id_book, title, publication_year, language, nb_pages, author_ida, category_idc) VALUES (124, 'Die Trying', 1998, 'English', 472, 56, 5);
INSERT INTO book (id_book, title, publication_year, language, nb_pages, author_ida, category_idc) VALUES (125, 'The Firm', 1991, 'English', 501, 57, 5);
INSERT INTO book (id_book, title, publication_year, language, nb_pages, author_ida, category_idc) VALUES (126, 'A Time to Kill', 1989, 'English', 515, 57, 5);
INSERT INTO book (id_book, title, publication_year, language, nb_pages, author_ida, category_idc) VALUES (127, 'The Pelican Brief', 1992, 'English', 436, 57, 5);
INSERT INTO book (id_book, title, publication_year, language, nb_pages, author_ida, category_idc) VALUES (128, 'The Black Echo', 1992, 'English', 496, 58, 4);
INSERT INTO book (id_book, title, publication_year, language, nb_pages, author_ida, category_idc) VALUES (129, 'The Lincoln Lawyer', 2005, 'English', 404, 58, 4);
INSERT INTO book (id_book, title, publication_year, language, nb_pages, author_ida, category_idc) VALUES (130, 'Gone Girl', 2012, 'English', 415, 59, 5);
INSERT INTO book (id_book, title, publication_year, language, nb_pages, author_ida, category_idc) VALUES (131, 'Sharp Objects', 2006, 'English', 254, 59, 5);
INSERT INTO book (id_book, title, publication_year, language, nb_pages, author_ida, category_idc) VALUES (132, 'The Girl on the Train', 2015, 'English', 336, 60, 5);
INSERT INTO book (id_book, title, publication_year, language, nb_pages, author_ida, category_idc) VALUES (133, 'Into the Water', 2017, 'English', 386, 60, 5);
INSERT INTO book (id_book, title, publication_year, language, nb_pages, author_ida, category_idc) VALUES (134, 'The Girl with the Dragon Tattoo', 2005, 'English', 465, 61, 4);
INSERT INTO book (id_book, title, publication_year, language, nb_pages, author_ida, category_idc) VALUES (135, 'The Girl Who Played with Fire', 2006, 'English', 503, 61, 4);
INSERT INTO book (id_book, title, publication_year, language, nb_pages, author_ida, category_idc) VALUES (136, 'The Snowman', 2007, 'English', 438, 62, 4);
INSERT INTO book (id_book, title, publication_year, language, nb_pages, author_ida, category_idc) VALUES (137, 'The Redbreast', 2000, 'English', 518, 62, 4);
INSERT INTO book (id_book, title, publication_year, language, nb_pages, author_ida, category_idc) VALUES (138, 'Faceless Killers', 1991, 'English', 288, 63, 4);
INSERT INTO book (id_book, title, publication_year, language, nb_pages, author_ida, category_idc) VALUES (139, 'The Dogs of Riga', 1992, 'English', 326, 63, 4);
INSERT INTO book (id_book, title, publication_year, language, nb_pages, author_ida, category_idc) VALUES (140, 'Half of a Yellow Sun', 2006, 'English', 433, 64, 1);
INSERT INTO book (id_book, title, publication_year, language, nb_pages, author_ida, category_idc) VALUES (141, 'Americanah', 2013, 'English', 477, 64, 1);
INSERT INTO book (id_book, title, publication_year, language, nb_pages, author_ida, category_idc) VALUES (142, 'Things Fall Apart', 1958, 'English', 209, 65, 1);
INSERT INTO book (id_book, title, publication_year, language, nb_pages, author_ida, category_idc) VALUES (143, 'No Longer at Ease', 1960, 'English', 169, 65, 1);
INSERT INTO book (id_book, title, publication_year, language, nb_pages, author_ida, category_idc) VALUES (144, 'Midnight''s Children', 1981, 'English', 536, 66, 1);
INSERT INTO book (id_book, title, publication_year, language, nb_pages, author_ida, category_idc) VALUES (145, 'The Satanic Verses', 1988, 'English', 547, 66, 1);
INSERT INTO book (id_book, title, publication_year, language, nb_pages, author_ida, category_idc) VALUES (146, 'Never Let Me Go', 2005, 'English', 288, 67, 2);
INSERT INTO book (id_book, title, publication_year, language, nb_pages, author_ida, category_idc) VALUES (147, 'The Remains of the Day', 1989, 'English', 258, 67, 1);
INSERT INTO book (id_book, title, publication_year, language, nb_pages, author_ida, category_idc) VALUES (148, 'Beloved', 1987, 'English', 324, 68, 1);
INSERT INTO book (id_book, title, publication_year, language, nb_pages, author_ida, category_idc) VALUES (149, 'Song of Solomon', 1977, 'English', 337, 68, 1);
INSERT INTO book (id_book, title, publication_year, language, nb_pages, author_ida, category_idc) VALUES (150, 'I Know Why the Caged Bird Sings', 1969, 'English', 289, 69, 10);
INSERT INTO book (id_book, title, publication_year, language, nb_pages, author_ida, category_idc) VALUES (151, 'The Color Purple', 1982, 'English', 295, 70, 1);
INSERT INTO book (id_book, title, publication_year, language, nb_pages, author_ida, category_idc) VALUES (152, 'Misery', 1987, 'English', 320, 8, 5);
INSERT INTO book (id_book, title, publication_year, language, nb_pages, author_ida, category_idc) VALUES (153, 'Carrie', 1974, 'English', 199, 8, 5);
INSERT INTO book (id_book, title, publication_year, language, nb_pages, author_ida, category_idc) VALUES (154, 'The Green Mile', 1996, 'English', 536, 8, 5);
INSERT INTO book (id_book, title, publication_year, language, nb_pages, author_ida, category_idc) VALUES (155, 'Pet Sematary', 1983, 'English', 374, 8, 5);
INSERT INTO book (id_book, title, publication_year, language, nb_pages, author_ida, category_idc) VALUES (156, 'Harry Potter and the Goblet of Fire', 2000, 'English', 636, 6, 3);
INSERT INTO book (id_book, title, publication_year, language, nb_pages, author_ida, category_idc) VALUES (157, 'Harry Potter and the Order of the Phoenix', 2003, 'English', 766, 6, 3);
INSERT INTO book (id_book, title, publication_year, language, nb_pages, author_ida, category_idc) VALUES (158, 'Harry Potter and the Half-Blood Prince', 2005, 'English', 607, 6, 3);
INSERT INTO book (id_book, title, publication_year, language, nb_pages, author_ida, category_idc) VALUES (159, 'Harry Potter and the Deathly Hallows', 2007, 'English', 607, 6, 3);
INSERT INTO book (id_book, title, publication_year, language, nb_pages, author_ida, category_idc) VALUES (160, 'A Feast for Crows', 2005, 'English', 753, 7, 3);
INSERT INTO book (id_book, title, publication_year, language, nb_pages, author_ida, category_idc) VALUES (161, 'A Dance with Dragons', 2011, 'English', 1016, 7, 3);
INSERT INTO book (id_book, title, publication_year, language, nb_pages, author_ida, category_idc) VALUES (162, 'Inferno', 2013, 'English', 461, 10, 5);
INSERT INTO book (id_book, title, publication_year, language, nb_pages, author_ida, category_idc) VALUES (163, 'Origin', 2017, 'English', 461, 10, 5);
INSERT INTO book (id_book, title, publication_year, language, nb_pages, author_ida, category_idc) VALUES (164, 'The Sun Also Rises', 1926, 'English', 251, 12, 1);
INSERT INTO book (id_book, title, publication_year, language, nb_pages, author_ida, category_idc) VALUES (165, 'This Side of Paradise', 1920, 'English', 305, 13, 1);
INSERT INTO book (id_book, title, publication_year, language, nb_pages, author_ida, category_idc) VALUES (166, 'Mansfield Park', 1814, 'English', 560, 14, 6);
INSERT INTO book (id_book, title, publication_year, language, nb_pages, author_ida, category_idc) VALUES (167, 'David Copperfield', 1850, 'English', 624, 15, 1);
INSERT INTO book (id_book, title, publication_year, language, nb_pages, author_ida, category_idc) VALUES (168, 'The Prince and the Pauper', 1881, 'English', 240, 16, 17);
INSERT INTO book (id_book, title, publication_year, language, nb_pages, author_ida, category_idc) VALUES (169, 'The Idiot', 1869, 'English', 656, 18, 1);
INSERT INTO book (id_book, title, publication_year, language, nb_pages, author_ida, category_idc) VALUES (170, 'The Autumn of the Patriarch', 1975, 'English', 269, 19, 1);

ALTER TABLE book ALTER COLUMN id_book RESTART WITH 171;
